### ISSUE TITLE
Make communication protocol machine readable instead of human readable

### ISSUE THREAD

**Issue by yannrenard** [OpenBCI/OpenBCI_32bit_Library#13]
Right now communication protocol sends (or may not send) replies in plain text, with information being (or not being) present depending on the current status of the board. It would be much easier for client code to be able to parse machine-ready replies formatted in JSON, XML or at least following a machine parseable format, especially including delimiters for begin and end of a reply. The content of the reply should be consistent across different device configuration, e.g. :

``` json
{
    "version" : 3,
    "max-channels" : 16,
    "on-board-ads1299" : "0x3E",
    "on-daisy-ads1299" : "0x3E",
    "has-daisy" : true,
}
```

(note the 'has-daisy' which would show-up even though daisy is not attached)

**Comment by pushtheworldllc** [comment]
this is just a good idea....

**Comment by pushtheworldllc** [comment]
@yannrenard what do you think about sending a different soft reset to indicate start with machine readable code. If you sent for example an `m` or something that indicates: `soft_reset` and ack back in JSON

**Comment by yannrenard** [comment]
would be awesome ! then make all the calls to send a reply, even though it is a simple 
```json
{
	"status" : "good"
}
```

:)

**Comment by pushtheworldllc** [comment]
Look at sending variable names as strings

**Comment by aj-ptw** [comment]
This has been done with the wifi shield.

**Comment by yannrenard** [comment]
awesome work @aj-ptw
