### ISSUE TITLE
Interrupt for ADS data ready pin

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_32bit_Library#22]
Check out ChipKit for examples of how to do this.

**Comment by pushtheworldllc** [comment]
Seems like a good guide: http://chipkit.net/wp-content/uploads/2016/02/MajenkoTech-AN1132-Working-with-chipKIT-Interrupts.pdf

**Comment by pushtheworldllc** [comment]
Another longer guide http://chipkit.net/wp-content/uploads/2015/05/chipKIT_PIC32_Interrupt_Handling.pdf

**Comment by pushtheworldllc** [comment]
@biomurph here are some good tutorials

**Comment by biomurph** [comment]
Hey! I poked around and figured out how to make interrupts work!
The code here has been tested:
https://github.com/biomurph/OpenBCI_32_Interrupt

**Comment by wjcroft** [comment]
Joel, very cool, thanks.

**Comment by aj-ptw** [comment]
This has been complete and can be found in all examples here https://github.com/OpenBCI/OpenBCI_32bit_Library/tree/2.0.0
