### ISSUE TITLE
Potential differences in data between stock OpenBCI firmware and Pushtheworld code

### ISSUE THREAD

**Issue by eohan** [OpenBCI/OpenBCI_32bit_Library#30]
I'm running Radio with https://github.com/pushtheworldllc/OpenBCI_Radios/releases/tag/v2.0.0-rc.2 and Firmware at https://github.com/pushtheworldllc/OpenBCI_32bit_Library/releases/tag/v2.0.0-rc.3 . But see that there is a difference in the noise floor and a particular ~31hz noise. The screenshot of the GUI in two different firmwares attached. I'm not sure if this is an issue. But would like to be tracked. 
Not that all the leads were floating and not connected to anything in both the cases.
The OpenBCI firmware
![stock_openbci firmware](https://cloud.githubusercontent.com/assets/518314/17145999/a815b162-532a-11e6-8d1b-887f712ad50d.png)
The pushtheworld firmware
![pushtheworld firmware](https://cloud.githubusercontent.com/assets/518314/17146006/b2474e52-532a-11e6-8103-da32dcb98c82.png)

**Comment by pushtheworldllc** [comment]
Verified they are the same. That 31Hz signal is most likely environmental noise with a combination of floating terminals.
