### ISSUE TITLE
upgrade guide links are broken

### ISSUE THREAD

**Issue by wjcroft** [OpenBCI/OpenBCI_32bit_Library#47]
reorganization of docs.openbci.com, broke the links.

**Comment by biomurph** [comment]
We have gone through and combed for broken links. I thought we fixed them all.
Can you tell me specifically where the broken ones are?

**Comment by wjcroft** [comment]
Joel, sorry, it's the tutorial links on this page,

https://github.com/OpenBCI/OpenBCI_32bit_Library/blob/master/UPGRADE_GUIDE.md

**Comment by biomurph** [comment]
Thanks William! Got 'em fixed!
