### ISSUE TITLE
Board does not send data when sampling higher rates v3.0.0

### ISSUE THREAD

**Issue by biomurph** [OpenBCI/OpenBCI_32bit_Library#52]
The new wifi supporting code does not send any data over the air when the sample rate is changed from 250 to any of the higher rates. Would it be nice if it would send at 250 even if it's sampling at higher rates? for example, if someone wants to write the higher rate to an SD card, they can still monitor the signal with the GUI or whatever...

**Comment by aj-ptw** [comment]
This will never be done. We do not want to stream any data to RFduino because the RFduino is how we intermittently send all channel values to ground because of some reflection over the lines.
